### ISSUE TITLE
diego-release bump to Envoy v3 bootstrap/config fields will break envoy-nginx config parser

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry-incubator/envoy-nginx-release#2]
See https://github.com/cloudfoundry-incubator/envoy-nginx-release/blob/46fba205621c605542d9c9d702e2a8c0601adaa2/src/code.cloudfoundry.org/envoy-nginx/parser/envoy_conf_parser.go#L11-L72

It appears the envoy boostrap config parser is hand-rolled in envoy-nginx. This will likely stop working once diego-release moves to configuring Envoy with purely v3 bootstrap configs/APIs, see: https://github.com/cloudfoundry/diego-release/issues/521

I would suggest leveraging https://github.com/envoyproxy/go-control-plane instead of the hand-rolled Go structs for bootstrap config parsing. This should ensure that when Envoy releases new API versions and deprecates older versions, it is as easy as bumping the `go-control-plane` dependency and adjusting import paths etc. rather than recreating Envoy config structs by hand.

**Note** Once diego-release changes to only use v3 configs are merged and released, there will likely be incompatibilities between envoy-nginx-release versions and diego-release versions that need to be taken into account when deploying these releases together. If possible, it would be desirable to future/past proof envoy-nginx to be able to parse Envoy bootstrap configs from multiple API versions.

**Comment by sunjayBhatia** [comment]
@aemengo, see https://github.com/cloudfoundry/diego-release/pull/526

The executor changes we made are here: https://github.com/cloudfoundry/executor/commit/23d8d6f82636bcebc3efe7dd3430d6b44a8e0f73

**Comment by aemengo** [comment]
We've decided against using the controlplane repo. It, ultimately, was too difficult to use with Golang's native `Unmarshal` parsers. But we have accommodated the v3 config updates.
